name: DiscordText
version: 1.0
main: discord.Main
api-version: 1.18
depend: [ProtocolLib, Vault]
commands:
  bp:
    description: "BackPack"
  ps:
    description: "Player Shop"
  am:
    description: "Auto Miner"
  dt:
    description: "Discord Text"
  dtsc:
    description: "Discord Staff Chat"