name: DiscordText
version: 1.0
main: lmp.Main
api-version: 1.18
depend: [ProtocolLib, Vault]
commands:
  bp:
    description: "BackPack"
  ps:
    description: "Player Shop"
  am:
    description: "Auto Miner"
  lmp:
    description: "LMP Server Command"
  dtsc:
    description: "Discord Staff Chat"
  twitch:
    description: "Twitch Bot"